DICT_ATTAQUES: dict[str, dict[str, str | int | None]] = {
    "Lance-Flammes": {
        "nom": "Lance-Flammes",
        "description": "L'ennemi reçoit un torrent de flammes.",
        "points_pouvoir": 15,
        "type_": "FEU",
        "classe": "spéciale",
        "puissance": 90,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Cru-Ailes": {
        "nom": "Cru-Ailes",
        "description": "L'ennemi est frappé par de larges ailes déployées pour infliger des dégâts.",
        "points_pouvoir": 35,
        "type_": "VOL",
        "classe": "physique",
        "puissance": 60,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Flammèche": {
        "nom": "Flammèche",
        "description": "L'ennemi est attaqué par une faible flamme.",
        "points_pouvoir": 25,
        "type_": "FEU",
        "classe": "spéciale",
        "puissance": 40,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Tranche": {
        "nom": "Tranche",
        "description": "Un coup de griffe ou autre tranche l'ennemi.",
        "points_pouvoir": 20,
        "type_": "NORMAL",
        "classe": "physique",
        "puissance": 70,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Déflagration": {
        "nom": "Déflagration",
        "description": "Un déluge de flammes ardentes submerge l'ennemi.",
        "points_pouvoir": 5,
        "type_": "FEU",
        "classe": "spéciale",
        "puissance": 110,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Aqua-Jet": {
        "nom": "Aqua-Jet",
        "description": "Le lanceur fonce sur l'ennemi si rapidement qu'on parvient à peine à le discerner.",
        "points_pouvoir": 20,
        "type_": "EAU",
        "classe": "physique",
        "puissance": 40,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Vibraqua": {
        "nom": "Vibraqua",
        "description": "Le lanceur envoie un puissant jet d'eau sur l'ennemi.",
        "points_pouvoir": 20,
        "type_": "EAU",
        "classe": "spéciale",
        "puissance": 60,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Morsure": {
        "nom": "Morsure",
        "description": "L'ennemi est mordu par de tranchantes canines.",
        "points_pouvoir": 25,
        "type_": "TENEBRES",
        "classe": "physique",
        "puissance": 60,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Hydro-Queue": {
        "nom": "Hydro-Queue",
        "description": "Le lanceur attaque en balançant sa queue comme une lame de fond en plein tempête.",
        "points_pouvoir": 10,
        "type_": "EAU",
        "classe": "physique",
        "puissance": 90,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Hydrocanon": {
        "nom": "Hydrocanon",
        "description": "Un puissant jet d'eau est dirigé sur l'ennemi.",
        "points_pouvoir": 5,
        "type_": "EAU",
        "classe": "spéciale",
        "puissance": 110,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Eclair": {
        "nom": "Eclair",
        "description": "Une décharge électrique tombe sur l'ennemi.",
        "points_pouvoir": 30,
        "type_": "ELECTRIK",
        "classe": "spéciale",
        "puissance": 40,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Tonnerre": {
        "nom": "Tonnerre",
        "description": "Une grosse décharge électrique tombe sur l'ennmi.",
        "points_pouvoir": 15,
        "type_": "ELECTRIK",
        "classe": "spéciale",
        "puissance": 90,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Eclair Fou": {
        "nom": "Eclair Fou",
        "description": "Une charge électrique violente.",
        "points_pouvoir": 15,
        "type_": "ELECTRIK",
        "classe": "physique",
        "puissance": 90,
        "stat_modifiee": None,
        "stat_niveau": None,
        "stat_pokemon": None,
    },
    "Armure": {
        "nom": "Armure",
        "description": "Le lanceur contracte tous ses muscles pour augmenter sa Défense.",
        "points_pouvoir": 30,
        "type_": "NORMAL",
        "classe": "statut",
        "puissance": None,
        "stat_modifiee": "defense",
        "stat_niveau": 1,
        "stat_pokemon": "attaquant",
    },
    "Gonflette": {
        "nom": "Gonflette",
        "description": "Le lanceur tend ses muscles pour se gonfler, ce qui booste son Attaque.",
        "points_pouvoir": 20,
        "type_": "COMBAT",
        "classe": "statut",
        "puissance": None,
        "stat_modifiee": "attaque",
        "stat_niveau": 1,
        "stat_pokemon": "attaquant",
    },
    "Croco Larme": {
        "nom": "Croco Larme",
        "description": (
            "Le lanceur fait semblant de pleurer pour troubler l'ennemi et beaucoup baisser sa Défense Spéciale."
        ),
        "points_pouvoir": 20,
        "type_": "TENEBRES",
        "classe": "statut",
        "puissance": None,
        "stat_modifiee": "defense_speciale",
        "stat_niveau": -2,
        "stat_pokemon": "attaqué",
    },
    "Grincement": {
        "nom": "Grincement",
        "description": "Le lanceur émet un son strident qui baisse beaucoup la Défense de l'ennemi.",
        "points_pouvoir": 40,
        "type_": "NORMAL",
        "classe": "statut",
        "puissance": None,
        "stat_modifiee": "defense",
        "stat_niveau": -2,
        "stat_pokemon": "attaqué",
    },
    "Rugissement": {
        "nom": "Rugissement",
        "description": (
            "Le lanceur pousse un cri tout mimi pour tromper la vigilance de l'ennemi et baisser son Attaque."
        ),
        "points_pouvoir": 40,
        "type_": "NORMAL",
        "classe": "statut",
        "puissance": None,
        "stat_modifiee": "attaque",
        "stat_niveau": -1,
        "stat_pokemon": "attaqué",
    },
    "Confidence": {
        "nom": "Confidence",
        "description": (
            "Dévoile des secrets à l'ennemi, qui perd alors sa concentration et voit son Attaque Spéciale diminuer."
        ),
        "points_pouvoir": 20,
        "type_": "NORMAL",
        "classe": "statut",
        "puissance": None,
        "stat_modifiee": "attaque_speciale",
        "stat_niveau": -1,
        "stat_pokemon": "attaqué",
    },
}
