# Ensemble de tous les types possibles
TYPES = {
    "ACIER",
    "COMBAT",
    "DRAGON",
    "EAU",
    "ELECTRIK",
    "FEE",
    "FEU",
    "GLACE",
    "INSECTE",
    "NORMAL",
    "PLANTE",
    "POISON",
    "PSY",
    "ROCHE",
    "SOL",
    "SPECTRE",
    "TENEBRES",
    "VOL",
}


# Dictionnaire de l'efficacité en fonction des types
TYPE_EFFICACITE = {
    "ACIER": {"ROCHE": 2.0, "ACIER": 0.5, "FEU": 0.5, "EAU": 0.5, "ELECTRIK": 0.5, "GLACE": 2.0, "FEE": 2.0},
    "COMBAT": {
        "NORMAL": 2.0,
        "VOL": 0.5,
        "POISON": 0.5,
        "ROCHE": 2.0,
        "INSECTE": 0.5,
        "SPECTRE": 0,
        "ACIER": 2.0,
        "PSY": 0.5,
        "GLACE": 2.0,
        "TENEBRES": 2.0,
        "FEE": 0.5,
    },
    "DRAGON": {"ACIER": 0.5, "DRAGON": 2.0, "FEE": 0.0},
    "EAU": {"SOL": 2.0, "ROCHE": 2, "FEU": 2.0, "EAU": 0.5, "PLANTE": 0.5, "DRAGON": 0.5},
    "ELECTRIK": {"VOL": 2.0, "SOL": 0.0, "EAU": 2.0, "PLANTE": 0.5, "ELECTRIK": 0.5, "DRAGON": 0.5},
    "FEE": {"COMBAT": 2.0, "POISON": 0.5, "ACIER": 0.5, "FEU": 0.5, "DRAGON": 2.0, "TENEBRES": 2.0},
    "FEU": {
        "ROCHE": 0.5,
        "INSECTE": 2.0,
        "ACIER": 2.0,
        "FEU": 0.5,
        "EAU": 0.5,
        "PLANTE": 2.0,
        "GLACE": 2.0,
        "DRAGON": 0.5,
    },
    "GLACE": {"VOL": 2.0, "SOL": 2.0, "ACIER": 0.5, "FEU": 0.5, "EAU": 0.5, "PLANTE": 2.0, "GLACE": 0.5, "DRAGON": 2.0},
    "INSECTE": {
        "COMBAT": 0.5,
        "VOL": 0.5,
        "POISON": 0.5,
        "SPECTRE": 0.5,
        "ACIER": 0.5,
        "FEU": 0.5,
        "PLANTE": 2.0,
        "PSY": 2.0,
        "TENEBRES": 2.0,
        "FEE": 0.5,
    },
    "NORMAL": {"ROCHE": 0.5, "SPECTRE": 0.0, "ACIER": 0.5},
    "PLANTE": {
        "VOL": 0.5,
        "POISON": 0.5,
        "SOL": 2.0,
        "ROCHE": 2.0,
        "INSECTE": 0.5,
        "ACIER": 0.5,
        "FEU": 0.5,
        "EAU": 2.0,
        "PLANTE": 0.5,
        "DRAGON": 0.5,
    },
    "POISON": {"POISON": 0.5, "SOL": 0.5, "ROCHE": 0.5, "SPECTRE": 0.5, "ACIER": 0.0, "PLANTE": 2.0, "FEE": 0.5},
    "PSY": {"COMBAT": 2.0, "POISON": 2.0, "ACIER": 0.5, "PSY": 0.5, "TENEBRES": 0.0},
    "ROCHE": {"COMBAT": 0.5, "VOL": 2.0, "SOL": 2.0, "INSECTE": 2.0, "ACIER": 0.5, "FEU": 2.0, "GLACE": 2.0},
    "SOL": {
        "VOL": 0.0,
        "POISON": 2.0,
        "ROCHE": 2.0,
        "INSECTE": 0.5,
        "ACIER": 2.0,
        "FEU": 2.0,
        "PLANTE": 0.5,
        "ELECTRIK": 2.0,
    },
    "SPECTRE": {"NORMAL": 0.0, "SPECTRE": 2.0, "PSY": 2.0, "TENEBRES": 0.5},
    "TENEBRES": {"COMBAT": 0.5, "SPECTRE": 2.0, "PSY": 2.0, "TENEBRES": 0.5, "FEE": 0.5},
    "VOL": {"COMBAT": 2.0, "ROCHE": 0.5, "INSECTE": 2.0, "ACIER": 0.5, "PLANTE": 2.0, "ELECTRIK": 2.0},
}
